// * Next
import type { Metadata } from "next";

// * NPM
import Main from "@/app/main";

// * MUI
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";

// * CSS
import "./globals.css";

export const metadata: Metadata = {
  title: "Hotel ERP",
  description: "Generated by create next app",
};

//* Fonts & Styles
import "@fontsource/abel";
import "@fontsource/rubik";
import "@fontsource/montez";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <InitColorSchemeScript attribute="class" />
        <Main>{children}</Main>
      </body>
    </html>
  );
}
