import type { Metadata } from "next";

//import "./globals.css";

import { ThemeProvider } from "next-themes";

// * NPM
import QueryProvider from "@/shared/QueryProvider";

export const metadata: Metadata = {
  title: "Hotel ERP",
  description: "Generated by create next app",
};

//* Fonts & Styles
import "@fontsource/abel";
import "@fontsource/rubik";
import "@fontsource/montez";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <>
          <QueryProvider>{children}</QueryProvider>
        </>
      </body>
    </html>
  );
}
